### ISSUE TITLE
Implement authentication using passport

### ISSUE THREAD

**Issue by sthb13** [sthb13/vef2-hopaverkefni1-sse#10]
Notendaumsjón skiptist í tvennt: óauðkenndur notandi og stjórnendur.

- Óauðkenndur notandi getur skoðað matseðil og sett í körfu.
- Óauðkenndur notandi getur sett mat af matseðli í körfu og fengið til baka auðkenni fyrir pöntun.
- Óauðkenndur notandi getur fylgst með stöðu pöntunar gegnum vefþjónustu og WS
- Stjórnendur geta breytt, bætt við, og eytt efni á matseðli
Þar sem óauðkenndur notandi útbýr pöntun skal það teljast nægjanlegt að sá notandi eigi auðkenni körfu/pöntunar til að mega sýsla með hana. Ekki er tiltekið hvernig notandi eigi að geyma þessi gögn, aðeins að það sé gert eftir að karfa er búin til.

Nota skal JWT með passport og geyma notendur i gagnagrunni. Útfæra þarf auðkenningu, nýskráningu notanda og middleware sem passar upp á heimildir stjórnenda.

Útbúa skal í byrjun einn stjórnanda með notandanafn admin og þekkt lykilorð, skrá skal lykilorð í README verkefnis.

**Comment by emh33** [comment]
Check : 
Nota skal JWT með passport og geyma notendur i gagnagrunni. Útfæra þarf auðkenningu, nýskráningu notanda og middleware sem passar upp á heimildir stjórnenda.

Útbúa skal í byrjun einn stjórnanda með notandanafn admin og þekkt lykilorð, skrá skal lykilorð í README verkefnis.
