### ISSUE TITLE
Add /menu

### ISSUE THREAD

**Issue by sthb13** [sthb13/vef2-hopaverkefni1-sse#12]
GET Skilar síðu af vörum á matseðli raðað í dagsetningar röð, nýjustu vörur fyrst
POST býr til nýja vöru á matseðil ef hún er gild og notandi hefur rétt til að búa til vöru, aðeins ef notandi sem framkvæmir er stjórnandi
Bæði er í lagi að taka við gögnum sem form data þar sem bæði mynd og gögn eru send inn, eða sem JSON og útfæra annað route sem tekur við mynd og festir við vöru, t.d. POST /menu/{id}/image

**Comment by sthb13** [comment]
`GET` Skilar síðu af vörum á matseðli raðað í dagsetningar röð, nýjustu vörur fyrst
`POST` býr til nýja vöru á matseðil ef hún er gild og notandi hefur rétt til að búa til vöru, aðeins ef notandi sem framkvæmir er stjórnandi
Bæði er í lagi að taka við gögnum sem form data þar sem bæði mynd og gögn eru send inn, eða sem JSON og útfæra annað route sem tekur við mynd og festir við vöru, t.d. POST /menu/{id}/image

**Comment by Stulli888** [comment]
Það þarf kannski að líta aftur á þetta þegar issue #9 er tekið en báðar vefþjónustur virka
