### ISSUE TITLE
Add /orders

### ISSUE THREAD

**Issue by sthb13** [sthb13/vef2-hopaverkefni1-sse#18]
- `GET` skilar síðu af pöntunum, nýjustu pantanir fyrst, aðeins ef notandi er stjórnandi
- `POST` býr til pöntun með viðeigandi gildum, skilar stöðu á pöntun og auðkenni

**Comment by emh33** [comment]
Held að það vantar hvernig  orders er tengt við  orderItems upp á það að geta náð í línu , ég ætla að taka mig af verkefninu núna þannig ef einhver vill kíkja á þetta :)
