### ISSUE TITLE
Add /orders/:id/status

### ISSUE THREAD

**Issue by sthb13** [sthb13/vef2-hopaverkefni1-sse#20]
- `GET` skilar pöntun með stöðu pöntunar og lista af öllum stöðubreytingum hennar
- `PATCH` uppfærir stöðu pöntunar, aðeins ef notandi er stjórnandi

**Comment by Stulli888** [comment]
Óli uppfærði verkefnislýsingu svo þetta er útfært sem GET og POST en ekki PATCH, eins og þetta er núna þá er hægt að breyta hvaða stöðu sem er í hvaða stöðu sem er svo lengi sem það er lögleg staða og sá sem er að breyta er admin
